package jogo.memoria;

import classes.Pontos;
import java.util.ArrayList;
/**
 *
 * @author aluno
 */
public class Recordes extends javax.swing.JInternalFrame {
    private ArrayList<Pontos> recordes;

   
    /**
     * Creates new form Recordes
     * @param recordes
     */
    public Recordes(ArrayList<Pontos> recordes) {
        
        initComponents();
        this.recordes = recordes;
        System.out.println("Alinhamento: "+this.getAlignmentX() + " x "+this.getAlignmentY());
        pontua();
    }
    public void pontua(){
        sort();
        
        String pnt = "<html><span style='color:red;'>Recordes:</span> <br>";
        for (int i = 0; i <this.recordes.size(); i++) {
            pnt +=  (recordes.get(i).getNome()+" - "+recordes.get(i).getValor()+" pontos <br>");
        }
        pnt += "</html>";
        recordeslbl.setText(pnt);
    }
     public ArrayList<Pontos> getRecordes() {
        return recordes;
    }


    public void setRecordes(ArrayList<Pontos> recordes) {
        this.recordes = recordes;
    }

    public void sort(){
        for (int i = 0; i < recordes.size(); i++) {
            for (int j = i; j < recordes.size()-1; j++) {
                if (recordes.get(j).getValor()<recordes.get(j+1).getValor()) {
                    Pontos p = recordes.get(j);
                    recordes.set(j, recordes.get(j+1));
                    recordes.set(j+1, p);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recordeslbl = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Recordes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/_icones/aang_icon.jpg"))); // NOI18N

        recordeslbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        recordeslbl.setText("Recordes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(recordeslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(recordeslbl)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        setBounds(0, 0, 396, 296);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel recordeslbl;
    // End of variables declaration//GEN-END:variables
}
